[package]
name = "indexing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "4.0"
regex = "1.5"
thiserror = "1.0"
tracing = "0.1"
unicode-normalization = "0.1"
walkdir = "2.3"
